# Generated by Django 4.2.6 on 2024-06-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('owner_id', models.CharField(max_length=36)),
            ],
            options={
                'db_table': 'lists',
            },
        ),
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=36, null=True)),
                ('completed_by', models.CharField(blank=True, max_length=36, null=True)),
                ('list_id', models.CharField(max_length=36, null=True)),
            ],
            options={
                'db_table': 'todos',
            },
        ),
    ]
