# Generated by Django 4.2.6 on 2023-10-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('owner_id', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=36)),
                ('completed_by', models.CharField(blank=True, max_length=36, null=True)),
                ('list_id', models.CharField(max_length=36)),
            ],
        ),
    ]
