# Generated by Django 4.2.6 on 2023-10-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_todo_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='list_id',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
